version: '24.0.2'

services:
  insight_file_components_service:
    build:
      dockerfile: Dockerfile
    environment:
      - ENV=prod
    env_file:
      - .env.prod
    ports:
      - "50052:50052"