# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_segment_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x66ile_segment_service.proto\",\n\x05\x46iles\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nfile_paths\x18\x02 \x03(\t\"F\n\x0b\x46ileSegment\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x12\n\nstart_line\x18\x02 \x01(\x05\x12\x10\n\x08\x65nd_line\x18\x03 \x01(\x05\x32@\n\x12\x46ileSegmentService\x12*\n\x10\x45xtractStructure\x12\x06.Files\x1a\x0c.FileSegment0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_segment_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILES']._serialized_start=30
  _globals['_FILES']._serialized_end=74
  _globals['_FILESEGMENT']._serialized_start=76
  _globals['_FILESEGMENT']._serialized_end=146
  _globals['_FILESEGMENTSERVICE']._serialized_start=148
  _globals['_FILESEGMENTSERVICE']._serialized_end=212
# @@protoc_insertion_point(module_scope)
