# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import file_components_service_pb2 as file__components__service__pb2


class FileComponentsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractFilesComponents = channel.unary_stream(
                '/FileComponentsService/ExtractFilesComponents',
                request_serializer=file__components__service__pb2.Files.SerializeToString,
                response_deserializer=file__components__service__pb2.FileComponent.FromString,
                )


class FileComponentsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExtractFilesComponents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileComponentsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractFilesComponents': grpc.unary_stream_rpc_method_handler(
                    servicer.ExtractFilesComponents,
                    request_deserializer=file__components__service__pb2.Files.FromString,
                    response_serializer=file__components__service__pb2.FileComponent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileComponentsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileComponentsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExtractFilesComponents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FileComponentsService/ExtractFilesComponents',
            file__components__service__pb2.Files.SerializeToString,
            file__components__service__pb2.FileComponent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
