# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_components_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x66ile_components_service.proto\",\n\x05\x46iles\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nfile_paths\x18\x02 \x03(\t\"H\n\rFileComponent\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x12\n\nstart_line\x18\x02 \x01(\x05\x12\x10\n\x08\x65nd_line\x18\x03 \x01(\x05\x32K\n\x15\x46ileComponentsService\x12\x32\n\x16\x45xtractFilesComponents\x12\x06.Files\x1a\x0e.FileComponent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_components_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILES']._serialized_start=33
  _globals['_FILES']._serialized_end=77
  _globals['_FILECOMPONENT']._serialized_start=79
  _globals['_FILECOMPONENT']._serialized_end=151
  _globals['_FILECOMPONENTSSERVICE']._serialized_start=153
  _globals['_FILECOMPONENTSSERVICE']._serialized_end=228
# @@protoc_insertion_point(module_scope)
