# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import file_chunks_service_pb2 as file__chunks__service__pb2


class FileChunksServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveFileChunks = channel.unary_unary(
                '/FileChunksService/SaveFileChunks',
                request_serializer=file__chunks__service__pb2.SaveFileChunksRequest.SerializeToString,
                response_deserializer=file__chunks__service__pb2.SaveFileChunksResponse.FromString,
                )
        self.GetSortedFileChunksContent = channel.unary_unary(
                '/FileChunksService/GetSortedFileChunksContent',
                request_serializer=file__chunks__service__pb2.GetSortedFileChunksContentRequest.SerializeToString,
                response_deserializer=file__chunks__service__pb2.GetSortedFileChunksContentResponse.FromString,
                )


class FileChunksServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveFileChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSortedFileChunksContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileChunksServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveFileChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveFileChunks,
                    request_deserializer=file__chunks__service__pb2.SaveFileChunksRequest.FromString,
                    response_serializer=file__chunks__service__pb2.SaveFileChunksResponse.SerializeToString,
            ),
            'GetSortedFileChunksContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSortedFileChunksContent,
                    request_deserializer=file__chunks__service__pb2.GetSortedFileChunksContentRequest.FromString,
                    response_serializer=file__chunks__service__pb2.GetSortedFileChunksContentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileChunksService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileChunksService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveFileChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FileChunksService/SaveFileChunks',
            file__chunks__service__pb2.SaveFileChunksRequest.SerializeToString,
            file__chunks__service__pb2.SaveFileChunksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSortedFileChunksContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FileChunksService/GetSortedFileChunksContent',
            file__chunks__service__pb2.GetSortedFileChunksContentRequest.SerializeToString,
            file__chunks__service__pb2.GetSortedFileChunksContentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
